### ISSUE TITLE
当画板内容尺寸较小时控件部分按钮无法使用

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [macvip/cover-drawio#1]
![思源笔记-bug反馈-15](https://user-images.githubusercontent.com/49649786/158597157-9b39725f-3f5e-4226-b516-2ded0a69756a.gif)

原因应该是控件无法监听到超过画板尺寸元素的鼠标悬浮事件

**Comment by macvip** [comment]
谢谢🙏
已在 v0.1.5 版本中修复
